module.exports = {
  Version20223: [
    'version-2022.3/getting-started/introduction',
    {
      type: 'category',
      label: 'Version 2022.3',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'version-2022.3',
        },

      ],
    },
  ]
}