module.exports = {
  Version20223: [
    'version-2022.3/getting-started/introduction',
    {
      type: 'category',
      label: 'Version 2022.3',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'version-2022.3',
        },

      ],
    },
  ],
  Version20224: [
    'version-2022.4/getting-started/introduction',
    {
      type: 'category',
      label: 'Version 2022.4',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'version-2022.4',
        },

      ],
    },
  ],
  Version20231: [
    'version-2023.1/getting-started/introduction',
    {
      type: 'category',
      label: 'Version 2023.1',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'version-2023.1',
        },

      ],
    },
  ],
  VersionOCT23: [
    'version-OCT 23/getting-started/introduction',
    {
      type: 'category',
      label: 'Version OCT 23',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'version-OCT 23',
        },

      ],
    },
  ],
}