module.exports = {
  learningSidebar: [
    'getting-started/introduction',
    {
      type: 'category',
      label: 'LEARN THE BASICS',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '01_getting-started/01_learn-the-basics',
        },

      ],
    },
    {
      type: 'category',
      label: 'PRE-REQUISITES',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '01_getting-started/02_prerequisites',
        },
      ]
    },
    {
      type: 'category',
      label: 'QUICK START',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '01_getting-started/03_quick-start',
        },
      ]
    },
    {
      type: 'category',
      label: 'GO TO THE NEXT LEVEL',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '01_getting-started/04_go-to-the-next-level',
        },

      ],
    },
    {
      type: 'category',
      label: 'Excel to Genesis - at speed',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '01_getting-started/06_excel-to-genesis-at-speed',
        },

      ],
    },
    {
      type: 'category',
      label: 'USE CASES',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '01_getting-started/07_use-cases',
        },

      ],
    },
	{
      type: 'category',
      label: 'DEVELOPER TRAINING',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '01_getting-started/08_developer-training',
        },

      ],
    },
    {
      type: 'category',
      label: 'GlOSSARY',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '01_getting-started/09_glossary',
        },

      ],
    },
  ],
  databaseSidebar: [
    'database/database-landing',
    {
      type: 'category',
      label: 'FIELDS, TABLES AND VIEWS',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '02_database/01_fields-tables-views',
        },

      ],
    },
    {
      type: 'category',
      label: 'DATABASE CONCEPTS',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '02_database/02_database-concepts',
        },
      ]
    },
    {
      type: 'category',
      label: 'DATA STRUCTURES',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '02_database/03_data-structures',
        },
      ]
    },
    {
      type: 'category',
      label: 'DATA TYPES',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '02_database/04_data-types',
        },
      ]
    },
    {
      type: 'category',
      label: 'DATABASE INTERFACE',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '02_database/05_database-interface',
        },
      ]
    },
    {
      type: 'category',
      label: 'HELPER CLASSES',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '02_database/06_helper-classes',
        },
      ]
    },
    {
      type: 'category',
      label: 'TYPES OF API',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '02_database/07_types-of-api',
        },
      ]
    },
    {
      type: 'category',
      label: 'DATABASE TECHNOLOGY',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '02_database/08_database-technology',
        },
      ]
    },
    {
      type: 'category',
      label: 'API REFERENCE',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '02_database/09_api-reference',
        },
      ]
    }
  ],
  serverModulesSidebar: [
    'server-modules/server-modules',
    {
      type: 'category',
      label: 'CONFIGURING RUNTIME',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '03_server-modules/01_configuring-runtime',
        },

      ],
    },
    {
      type: 'category',
      label: 'DATA SERVER',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '03_server-modules/02_data-server',
        },

      ],
    },
    {
      type: 'category',
      label: 'REQUEST SERVER',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '03_server-modules/03_request-server',
        },

      ],
    },
    {
      type: 'category',
      label: 'EVENT HANDLER',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '03_server-modules/04_event-handler',
        },

      ],
    },
    {
      type: 'category',
      label: 'ACCESS CONTROL',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '03_server-modules/05_access-control',
        },

      ],
    },
    {
      type: 'category',
      label: 'STATE MACHINE',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '03_server-modules/06_state-machine',
        },

      ],
    },
    {
      type: 'category',
      label: 'CONSOLIDATOR',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '03_server-modules/07_consolidator',
        },

      ],
    },
    {
      type: 'category',
      label: 'EVALUATOR',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '03_server-modules/08_evaluator',
        },

      ],
    },
    {
      type: 'category',
      label: 'INTER-PROCESS MESSAGES',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '03_server-modules/09_inter-process-messages',
        },

      ],
    },
    {
      type: 'category',
      label: 'INTEGRATION',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '03_server-modules/10_integration',
        },

      ],
    },
    {
      type: 'category',
      label: 'TOOLING',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '03_server-modules/11_tooling',
        },

      ],
    }
  ],
  frontendSidebar: [
    'front-end/front-end',
    {
      type: 'category',
      label: 'BASICS',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '04_front-end/01_basics',
        },

      ],
    },
    {
      type: 'category',
      label: 'WEB COMPONENTS',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '04_front-end/02_web-components',
        },

      ],
    },
    {
      type: 'category',
      label: 'DESIGN SYSTEMS',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '04_front-end/03_design-systems',
        },

      ],
    },
    {
      type: 'category',
      label: 'INTEGRATIONS',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '04_front-end/04_integrations',
        },

      ],
    },
    {
      type: 'category',
      label: 'MICRO FRONT-ENDS',
      collapsed: false,
      items: [
        {
          type: 'doc',
					id: 'front-end/micro-front-ends/introduction'
        },
        {
          type: 'doc',
					id: 'front-end/micro-front-ends/front-end-reporting'
        },
        {
          type: 'doc',
					id: 'front-end/micro-front-ends/foundation-header'
        },
        {
          type: 'doc',
					id: 'front-end/micro-front-ends/foundation-entity-management'
        },
      ],
    },
    {
      type: 'category',
      label: 'DEPLOYING',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '04_front-end/06_deploying',
        },

      ],
    }
  ],
  operationsSidebar: [
    'operations/operations',
    {
      type: 'category',
      label: 'SERVER SETUP',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '05_operations/01_server-setup',
        },
      ],
    },
    {
      type: 'category',
      label: 'COMMANDS',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '05_operations/02_commands',
        },

      ],
    },
    {
      type: 'category',
      label: 'CLUSTERING',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '05_operations/03_clustering',
        },

      ],
    },
    {
      type: 'category',
      label: 'GEM',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '05_operations/04_gem',
        },

      ],
    },
    {
      type: 'category',
      label: 'CONSOLE',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '05_operations/05_console',
        },

      ],
    },
    {
      type: 'category',
      label: 'TESTING',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '05_operations/06_testing',
        },

      ],
    },
    {
      type: 'category',
      label: 'METRICS',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '05_operations/07_metrics',
        },

      ],
    },
    {
      type: 'category',
      label: 'ARTIFACTORY',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '05_operations/08_artifactory',
        },

      ],
    }
  ]
}
