/**
 * Auto-generated by generate-api-docs.js — do not edit by hand.
 * Remove a package entry (or run with --force) to trigger regeneration.
 */
module.exports = {
  "@genesislcap/foundation-login": "14.352.0",
  "@genesislcap/foundation-comms": "14.352.0",
  "@genesislcap/foundation-entity-management": "14.352.0",
  "@genesislcap/grid-pro": "14.352.0",
  "@genesislcap/grid-tabulator": "14.352.0",
  "@genesislcap/g2plot-chart": "14.352.0",
  "@genesislcap/foundation-forms": "14.352.0",
  "@genesislcap/foundation-i18n": "14.352.0",
  "@genesislcap/foundation-fdc3": "14.352.0",
  "@genesislcap/foundation-openfin": "14.352.0",
  "@genesislcap/foundation-notifications": "14.352.0",
  "@genesislcap/foundation-layout": "14.352.0",
  "@genesislcap/foundation-store": "14.352.0",
  "@genesislcap/foundation-redux": "14.352.0",
  "@genesislcap/foundation-testing": "14.352.0",
  "@genesislcap/foundation-utils": "14.352.0",
  "@genesislcap/foundation-criteria": "14.352.0",
  "@genesislcap/foundation-header": "14.352.0",
  "@genesislcap/expression-builder": "14.352.0",
};
