---
format: md
---
<!-- Do not edit this file. It is automatically generated by API Documenter. -->

[Home](./index.md) &gt; [@genesislcap/grid-pro](./grid-pro.md) &gt; [SelectEditor](./grid-pro.selecteditor.md) &gt; [init](./grid-pro.selecteditor.init.md)

## SelectEditor.init() method

**Signature:**

```typescript
init(params: SelectEditorParams): void;
```

## Parameters

|  Parameter | Type | Description |
|  --- | --- | --- |
|  params | [SelectEditorParams](./grid-pro.selecteditorparams.md) |  |

**Returns:**

void

