import { AIService, AIServiceConfig } from './types';
import { createAIRepository, AIRepository } from '../../repositories/ai';
import { Services } from '../../types/services';
import { Result } from '../../types/result';

/**
 * AI Service implementation
 * 
 * This service wraps the AI repository and provides business logic
 * for AI-powered documentation analysis.
 */
export class RealAIService implements AIService {
  private aiRepository: AIRepository;

  constructor(config: AIServiceConfig) {
    // Create the underlying AI repository
    this.aiRepository = createAIRepository({
      useMock: config.useMock
    });

    console.log(`🤖 AI Service initialized`);
  }

  /**
   * Analyzes a commit hash to determine if documentation updates are needed
   * @param services - The services object containing git and ai services
   * @param commitHash - The git commit hash to analyze
   * @returns Promise<Result<boolean, string>> - Success with boolean indicating if docs should be updated, or error with failure reason
   */
  async shouldUpdateDocs(services: Services, commitHash: string): Promise<Result<boolean, string>> {
    try {
      console.log(`🔍 Analyzing commit ${commitHash} for documentation update requirements`);

      // Step 1: Pull latest changes from foundation-ui repository
      console.log('📥 Pulling latest changes from foundation-ui repository...');
      const pullResult = await services.git.pullLatest('foundation-ui');
      if (Result.isError(pullResult)) {
        return Result.error(`Failed to pull latest changes from foundation-ui repository: ${pullResult.message.message}`);
      }

      // Step 2: Get commit information
      console.log('📋 Getting commit information...');
      const commitResult = await services.git.getCommitInfo(commitHash, 'foundation-ui');
      if (Result.isError(commitResult)) {
        return Result.error(`Failed to get commit information: ${commitResult.message.message}`);
      }

      const commitInfo = commitResult.value;
      console.log(`📝 Commit: ${commitInfo.message} by ${commitInfo.author}`);

      // Step 3: Check for automated commits from semantic-release-bot
      if (commitInfo.author === 'semantic-release-bot') {
        console.log('🤖 Detected automated commit from semantic-release-bot - no docs update needed');
        return Result.success(false);
      }

      // Step 4: Check if the commit changed autogenerated API markdown docs
      const apiDocsChanged = this.hasApiDocsChanges(commitInfo);
      if (apiDocsChanged) {
        console.log('📚 Detected changes to autogenerated API docs - docs update required');
        return Result.success(true);
      }

      // Step 5: Use AI to analyze the commit
      console.log('🤖 Using AI to analyze commit for documentation update requirements...');
      const aiResult = await this.aiRepository.shouldUpdateDocs(services, commitInfo);
      
      if (Result.isSuccess(aiResult)) {
        const needsUpdate = aiResult.value;
        console.log(`🤖 AI Analysis Result: ${needsUpdate ? 'Documentation updates needed' : 'No documentation updates required'}`);
        return Result.success(needsUpdate);
      } else {
        console.log(`❌ AI Analysis Error: ${aiResult.message}`);
        return Result.error(`AI analysis failed: ${aiResult.message}`);
      }

    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
      console.error('❌ Error in shouldUpdateDocs:', errorMessage);
      return Result.error(`Error analyzing commit for documentation updates: ${errorMessage}`);
    }
  }

  /**
   * Checks if the commit changed autogenerated API markdown documentation
   * @param commitInfo - The commit information
   * @returns boolean - True if API docs were changed
   */
  private hasApiDocsChanges(commitInfo: any): boolean {
    // Look for changes to autogenerated API markdown files
    const apiDocsPatterns = [
      /\.md$/i, // Markdown files
      /api/i,   // Files with "api" in the name
      /docs/i   // Files with "docs" in the path
    ];

    return commitInfo.filesChanged.some((file: string) => {
      return apiDocsPatterns.some(pattern => pattern.test(file));
    });
  }
}

/**
 * Factory function to create an AI service
 * @param config - Configuration for the AI service
 * @returns AIService - The configured AI service
 */
export function createAIService(config: AIServiceConfig): AIService {
  return new RealAIService(config);
} 