name: Deploy to production archive

on:
  # Manually triggered
  workflow_dispatch:
  # And temporarily when a PR is raised for testing purposes
  pull_request:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
        scope: '@genesislcap'

    - name: Bootstrap
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{secrets.GPR_READ_TOKEN}}

    # When deploying to a subfolder, set the BASE_URL below so static assets are resolved correctly
    - name: Build
      run: npm run build
      env:
        BASE_URL: /archive/

    - uses: jakejarvis/s3-sync-action@master
      with:
        # TODO re-instate delete: args: --follow-symlinks --delete
        args: --follow-symlinks
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #AWS_S3_BUCKET: genesis-portal
        AWS_S3_BUCKET: genesis-internal-web
        AWS_REGION: 'eu-west-2'
        SOURCE_DIR: 'build'
        DEST_DIR: 'archive'


