name: 'Deploy to low-code (v2 docs)'

on:
  push:
    branches: [ PTF-50-low-code ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
        scope: '@genesislcap'

    - name: Bootstrap
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{secrets.GPR_READ_TOKEN}}

    # When deploying to a subfolder, set the BASE_URL below
    # so static assets are resolved correctly
    - name: Build
      run: npm run build
      env:
        BASE_URL: /low-code/secure/

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: genesis-internal-web
        AWS_REGION: 'eu-west-2'
        SOURCE_DIR: 'build'
        DEST_DIR: 'low-code/secure'


