name: Hard Reset Branch

on:
  workflow_dispatch:
    inputs:
      branch_to_reset:
        description: 'Branch to hard reset'
        required: true
        default: 'pk/hard-reset-workflow' # Change to master once tested
  push:
